### ISSUE TITLE
Misaka / ToaruOS 2.0 Roadmap

### ISSUE THREAD

**Issue by klange** [toaruos/misaka#1]
- [x] Kernel Elf loader
   - [x] Support Elf64 binaries in basic parsing.
   - [x] Support necessary relocations for object files used as modules.
   - [x] Support static binary loading for userspace.
- [x] Memory Allocation Support
   - [x] Basic PML4 page allocator
   - [x] Set up kernel heap with klmalloc
   - [ ] _Next:_ Add a more capable mmap interface 
- [x] Task Switching
   - [x] Port process model
   - [x] Interrupt infrastructure with legacy PIC, etc.
   - [ ]  _Next:_ APIC, LAPIC... 
- [x] Virtual File System
   - [x] Port existing VFS infrastructure
   - [x] Port tmpfs, tarfs modules
   - [ ] Port drivers for storage devices
   - [ ] _Next:_ Re-write PATA drivers, rewrite ext2 driver, SATA drivers
- [x] Syscall functionality
   - [x] Port existing syscalls
   - [x] Port TTY layer, PacketFS
   - [ ] _Next:_ Implement support for new syscall interfaces 
- [x] Userspace
   - [x] Port ld.so dynamic linker to support Elf64.
   - [x] Verify functionality of libc in x86-64.
   - [x] Verify functionality of existing applications, resolve word size issues. 
- [ ] Remaining driver ports:
   - [ ] Network Stack
      - [ ] Main network stack (or dump this because it's terrible and just write a new one?)
      - [x] e1000
      - [ ] rtl8139
      - [ ] pcnet 
   - [ ] Audio
      - [x] Core mixer
      - [x] ac97
      - [ ] pcspk (this should be portable right now? don't forget to adjust timings)
      - [ ] _Next:_ Intel HDA 
   - [ ] Storage
      - [ ] ATA/ATAPI driver
      - [ ] Ext2 filesystem driver (this is really broken, rewrite it?)
      - [ ] ISO9660
   - [x] VirtualBox guest driver
