### ISSUE TITLE
Ports Checklist

### ISSUE THREAD

**Issue by klange** [toaruos/misaka#2]
- [x] binutils
   - Had to disable readline - investigate this. I think the last thing it wanted was newer signals API. Would be nice to implement `ptrace` and port `gdb`, which was what needed `readline`.
- [x] doom-generic
- [ ] gcc
   - Might just need to dump gmp/mpc/mpfr in the source tree and see what happens.
- [ ] SDL 1.2
- [ ] Bochs
- [ ] Quake (sdlquake)
- [ ] muPDF
   - This was skipped in NIH because it had several deps and it was pain to rebuild them, but it should be explored again.
- [ ] Python
   - Try to port latest release (3.10?) and fix build issues; see if we can upstream any necessary patches.
- [ ] freetype, cairo, other small libs
   - All of these should just build; build the extension plugins as well for the compositor.
- [ ] mbedTLS or whatever 
- [ ] curl or wget
   - Or both... when the socket API is completed, having one of these common tools available would be great.
